name: PPTX to PDF Conversion

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: checking github connection
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git clone ***github.com/kreatewebsite/kreate_output # This works
          ls
#           cd kreate_output
#           git config user.name "Dev-98"
#           git config user.email "devparker48@gmail.com"
#           git config --unset-all http.https://github.com/.extraheader

#           git add "Portfolio"/
#           git commit -m "Add converted images from PDF"

#           git push --set-upstream origin main
