name: PPTX to Images Conversion

on:
  push:
    branches:
      - main

jobs:
  convert_to_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#       - name: Install Dependencies
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y libreoffice poppler-utils

      - name: Find PPTX Files
        id: find_pptx_files
        run: |
          find input/content -name "*.pptx" -type f > pptx_files.txt
          cat pptx_files.txt
           
      - name: Convert PPTX to PDF and Images
        run: |
          mkdir -p artifacts/images

          while IFS= read -r ppt_file; do
            ppt_name=$(basename "$ppt_file" .pptx)
            cat "$ppt_name"
            cat "$ppt_file"
          done < pptx_files.txt

