name: PPTX to PDF Conversion

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:

  convert_to_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install LibreOffice
        run: |
          sudo apt-get update 
          sudo apt-get install -y libreoffice

      - name: Convert PPTX to PDF
        run: |
        
          libreoffice --headless --convert-to pdf pinecone.pptx

      - name: Create Artifacts Directory
        run: mkdir pinecone

      - name: Move PDF to Artifacts Directory
        run: mv pinecone.pdf pinecone/ || true
      
      - name: Checking something
        run: ls -a
        
      - name: Upload Artifact - PDF
        uses: actions/upload-artifact@v2
        with:
          name: converted-pdfs
          path: pinecone/

      - name: Checkout Output Repository
        uses: actions/checkout@v2
        with:
          repository: kreatewebsite/kreate_output
          token: ${{ secrets.TOKEN }}
          ref: main
        
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: converted-pdfs
          path: pinecone

      - name: Move PDF to Output Repository
        run: |
          ls -a

      - name: Commit and Push PDF to Output Repository
        run: |
          
          git config --global user.name "Dev-98"
          git config --global user.email "devparker48@gmail.com"
          git add .
          git commit -m "Add PDF output"
          git push origin main
