name: PPTX to PDF Conversion

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Output Repository
        uses: actions/checkout@v2
        with:
          repository: kreatewebsite/kreate_output
          token: ${{ secrets.TOKEN }}
          ref: main

      - name: Move PDF to Output Repository
        run: |
          cp input/* ./kreate_output/
        working-directory: ./
