name: PPTX to PDF Conversion

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install LibreOffice
        run: |
          sudo apt update 
          sudo apt install libreoffice

      - name: Convert PPTX to PDF
        run: |
          libreoffice --headless --convert-to pdf Portfolio.pptx

      - name: Create Artifacts Directory
        run: mkdir artifacts

      - name: Move PDF to Artifacts Directory
        run: mv Portfolio.pdf artifacts/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: converted-pdfs
          path: artifacts/
