name: Convert PPT to Images and Save in Another Repo

on:
  push:
    branches:
      - main
   
jobs:
  get_ppt_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get PPT File Name
        id: get_ppt_name
        run: |
          ppt_file=$(find input -name "*.pptx")
          ppt_name=$(basename "$ppt_file" .pptx)
          echo "Output of this $ppt_name"
          
          # Export the variable so that it can be used in subsequent steps and jobs
          echo "export PPT_NAME=$ppt_name" >> $GITHUB_ENV
          
    outputs:
      ppt_name: ${{steps.get_ppt_name.outputs.ppt_name}}
            
  convert_ppt_to_pdf:
    runs-on: ubuntu-latest
    needs: get_ppt_name

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Poppler and Libreoffice
        run: |
          sudo apt-get update 
          sudo apt-get install -y poppler-utils
          sudo apt update 
          sudo apt install libreoffice

      - name: Convert PPT to PDF and Create Artifact
        run: |

          # Your commands to convert PPT to PDF using an appropriate tool (e.g., LibreOffice)
          # Example using LibreOffice:
            
          soffice --headless --convert-to pdf "$PPT_NAME".pptx
          
          # Move the generated PDF to a location where artifacts can pick it up
          mv "$PPT_NAME".pdf $GITHUB_WORKSPACE/"$PPT_NAME".pdf
       
      - name: Verify PDF Output
        run: |
          # List files in the current directory to check if the PDF was generated
          ls -la

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-pdf
          path: "$PPT_NAME.pdf"
        
          
  convert_pdf_to_images:
    runs-on: ubuntu-latest
    needs: [convert_ppt_to_pdf, get_ppt_name]

    steps:
      - name: Download PDF Artifact
        uses: actions/download-artifact@v2
        with:
          name: my-pdf

      - name: Convert PDF to Images
        run: |
          # Create a directory to store the images
          mkdir "$PPT_NAME"

          # Convert PDF to images using pdftoppm
          pdftoppm -png "$PPT_NAME".pdf "$PPT_NAME"/slide

      - name: Clone Another Repo
        run: |
          git config --global user.email "devparker48@gmail.com"
          git config --global user.name "Dev-98"
          git clone https://github.com/dataknobs/kreatewebsites-intermediate/tree/main/Dev-98 other_repo

      - name: Move Images to Another Repo
        run: |
          mv images other_repo/"$PPT_NAME"

      - name: Commit and Push Changes to Another Repo
        run: |
          cd other_repo
          git add .
          git commit -m "Add converted images"
          git push

      - name: Clean Up
        run: |
          rm -rf "$PPT_NAME"
          rm my_presentation.pdf

